export default {
  login: "davglass",
  id: 32551,
  node_id: "MDQ6VXNlcjMyNTUx",
  avatar_url: "https://avatars.githubusercontent.com/u/32551?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/davglass",
  html_url: "https://github.com/davglass",
  followers_url: "https://api.github.com/users/davglass/followers",
  following_url: "https://api.github.com/users/davglass/following{/other_user}",
  gists_url: "https://api.github.com/users/davglass/gists{/gist_id}",
  starred_url: "https://api.github.com/users/davglass/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/davglass/subscriptions",
  organizations_url: "https://api.github.com/users/davglass/orgs",
  repos_url: "https://api.github.com/users/davglass/repos",
  events_url: "https://api.github.com/users/davglass/events{/privacy}",
  received_events_url: "https://api.github.com/users/davglass/received_events",
  type: "User",
  site_admin: false,
  name: "Dav Glass",
  company: "@medicalert-foundation-inc ",
  blog: "https://foobar.social/web/@davglass",
  location: "Marion, IL",
  email: null,
  hireable: null,
  bio: "Currently taking a much needed sabbatical from Open Source and technology, please respect. Former Yahoo/Verizon Open Source guy. I'm also the creator of @HackSI",
  twitter_username: "davglass",
  public_repos: 223,
  public_gists: 354,
  followers: 953,
  following: 113,
  created_at: "2008-11-04T04:22:29Z",
  updated_at: "2022-11-08T19:43:53Z"
}
